### ISSUE TITLE
Initial public alpha release

### ISSUE THREAD

**Issue by sayplastic** [lbryio/lbryweb.go#3]
## Checklist for the public alpha:

- [x] content navigation
- [x] streaming video content playback with skipping feature
- [x] ~improve streaming module to be able to set write timeouts (#8)~ turned out to be complex, deferred until there's more time for this
- [x] implement regular formats playback (#9)
- [x] [UI server](https://github.com/lbryio/lbry-desktop/issues/2299)
- [x] [disabled features in js](https://github.com/lbryio/lbry-desktop/issues/2300)

## Features planned for the next version: 

- [ ] accounts
- [ ] wallets
